const imageLinks = [
  { id: 1, url: "https://imgur.com/a/q3PcDw5" },
  { id: 2, url: "https://imgur.com/wl14ONP" },
  { id: 3, url: "https://imgur.com/Spb4V7d" },
  { id: 4, url: "https://imgur.com/Mql64HJ" },
  { id: 5, url: "https://imgur.com/5ElBS5r" },
  { id: 6, url: "https://imgur.com/msq7y7V" },
  { id: 7, url: "https://imgur.com/LoaCJ68" },
  { id: 8, url: "https://imgur.com/ArPTsAW" },
  { id: 9, url: "https://imgur.com/Kp9FFUy" },
  { id: 10, url: "https://imgur.com/20ISINW" },
  { id: 11, url: "https://imgur.com/AQfPqLJ" },
  { id: 12, url: "https://imgur.com/rJNTPke" },
  { id: 13, url: "https://imgur.com/Qx9bgzP" },
  { id: 14, url: "https://imgur.com/pwyyfSV" },
  { id: 15, url: "https://imgur.com/ewwvIFf" },
  { id: 16, url: "https://imgur.com/52zlk8j" },
  { id: 17, url: "https://imgur.com/Y7x0c8E" },
  { id: 18, url: "https://imgur.com/A48KMlZ" },
  { id: 19, url: "https://imgur.com/namRbRi" },
  { id: 20, url: "https://imgur.com/YhDdkwt" },
  { id: 21, url: "https://imgur.com/jGIlulb" },
  { id: 22, url: "https://imgur.com/ZWZ58N6" },
  { id: 23, url: "https://imgur.com/Sp79UL4" },
  { id: 24, url: "https://imgur.com/dPDSgkj" },
  { id: 25, url: "https://imgur.com/rE1685U" },
  { id: 26, url: "https://imgur.com/QUHBtip" },
  { id: 27, url: "https://imgur.com/dbVveoP" },
  { id: 28, url: "https://imgur.com/wQG9Nfm" },
  { id: 29, url: "https://imgur.com/ZpFBZl1" },
  { id: 30, url: "https://imgur.com/9wITUS7" },
];

export default imageLinks;
